### ISSUE TITLE
Adapt goth to yagna decentralized market implementation

### ISSUE THREAD

**Issue by zakaprov** [golemfactory/goth#303]
Since yagna version [`v0.4.0-alpha.0`](https://github.com/golemfactory/yagna/tree/v0.4.0-alpha.0) the nodes are using a decentralized market implementation by default. This means that `goth` should move away from using a centralized market container in its setup.

Steps that need to be done identified so far:
- [x] Remove the `mock-api` container from `docker-compose.yml`,
- [x] Remove references to the market from `address.py`, along with their usage (e.g. `MARKET_API_URL`, `CENTRAL_MARKET_URL`),
- [x] Make sure the routing in `router_addon.py` is still valid,
- [ ] Assess feasibility of intercepting GSB market traffic.

**Comment by stranger80** [comment]
...should this be moved to Done?
