### ISSUE TITLE
Enable running probes on the host machine

### ISSUE THREAD

**Issue by kmazurek** [golemfactory/goth#361]
The `Probe` class currently assumes that the yagna daemon it's controlling is running inside a Docker container. To simplify use cases such as the interactive mode of `goth` (see: #358) it'd make sense to make `Probe` more general and allow it to run with a yagna daemon on the host machine as well.

TODO
- [ ] move logic that's common for all probe types to an abstract base class
- [x] create a separate class for host-based probes
- [x] implement a CLI module to interact with a local yagna daemon
- [ ] adapt file logging to work with both probe types
- [ ] integrate with current solution for generating payment IDs (#346)
